#184637119 Set up an empty Express Boilerplate with dotenv
atlp-rwanda/destructors-ec-bn pull request #1
Opened 2023-03-07 20:25 UTC by mjeanbosco19

**What does this PR do?**

- Set up an empty Express Boilerplate with dotenv.

**Description of Task to be completed?**

- Set up an empty Node.js - express application.  Full directory with all folders that you think developer will need

**How should this be manually tested?**

- Clone the project and use the terminal to start the development server by "npm run dev"

**Any background context you want to provide?**

- none

**What are the relevant pivotal tracker/Trello stories?**

- Tracker: 184637119

**Screenshots (if appropriate)**

- none

**Questions:**

- none

2023-03-07 20:32 UTC, denislohan requested changes
rename the commit mesage by removing the task id,

2023-03-07 21:56 UTC, mjeanbosco19 commented
> rename the commit mesage by removing the task id,

Thanks, I have completed to rename the commit message.

2023-03-08 04:12 UTC, Abdulkeza requested changes
Nice Job @mjeanbosco19 , but I can't see all folders as required.
also, I left some feedback bellow

2023-03-08 04:12 UTC, Abdulkeza commented on src/index.js
> +dotenv.config();
You can change this into  a single line by using `import 'dotenv/config'`

2023-03-08 06:06 UTC, leandreAlly commented on src/index.js
> +dotenv.config();
@Abdulkeza  Thanks for this pro tips!

2023-03-08 06:58 UTC, Abdulkeza approved these changes
Nice work @mjeanbosco19 .

2023-03-08 07:09 UTC, katros1 approved these changes

2023-03-08 07:09 UTC, divinecharlotte approved these changes
# Hello @mjeanbosco19    😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers and Happy coding!👏👏👏

2023-03-08 07:12 UTC, mjeanbosco19 commented
> # Hello @mjeanbosco19 😃 🥳 🎉 🎈
> Great Job 😄 👏 You've done it. There is nothing else to say other than... it's time to merge it 👍🏻 ✅
> 
> ![](https://camo.githubusercontent.com/7f4fd1ee2d3cc47007a12ab009e6dd3d4971c0240fd9476d7485954b937ae942/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f334b43326a44325163424f53632f67697068792e676966) [ ![68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f334b43326a44325163424f53632f67697068792e676966](https://camo.githubusercontent.com/7f4fd1ee2d3cc47007a12ab009e6dd3d4971c0240fd9476d7485954b937ae942/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f334b43326a44325163424f53632f67697068792e676966) ](https://camo.githubusercontent.com/7f4fd1ee2d3cc47007a12ab009e6dd3d4971c0240fd9476d7485954b937ae942/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f334b43326a44325163424f53632f67697068792e676966) [ ](https://camo.githubusercontent.com/7f4fd1ee2d3cc47007a12ab009e6dd3d4971c0240fd9476d7485954b937ae942/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f334b43326a44325163424f53632f67697068792e676966)
> 
> Cheers and Happy coding!👏👏👏

Thanks @divinecharlotte

2023-03-08 08:52 UTC, merged