#184637135 feat:google-login-authentication
atlp-rwanda/destructors-ec-bn pull request #10
Opened 2023-03-10 09:23 UTC by buka1calvin

#### What does this PR do?
As a user, I can login in to the app  via Google.
#### Description of Task to be completed?
Currently as a new user cannot login with their pre-existing social media accounts. He/She can only login with email password combinations.
as a new user i should be able to login with google 
* here are some end points you can use for testing
  `GET /api/v1/users`:for getting the path to the google login form
  `GET /api/v1/users/login`:here you can login directly
  `GET /api/v1/users/google/callback`:this is the link that will direct you after a successful login
   `GET /api/v1/users/protected`:this is the page you're directed in
   `GET /api/v1/users/failure`:this is the page redirected when the the actual page is not available
   
#### How should this be manually tested?
after cloning the repo, cd into it and RUN : `npm run dev`
then you can  test the endpoints provided above using postman or your browser preferably

#### Any background context you want to provide?
this is the google authentication for users 

#### What are the relevant pivotal tracker/Trello stories
#184637138

2023-03-17 09:36 UTC, mjeanbosco19 requested changes
@buka1calvin 
Resolve conflict

2023-03-20 14:20 UTC, katros1 approved these changes

2023-03-20 15:12 UTC, Abdulkeza commented on src/services/googleAuth.js
> +        // done(null, user);
remove this

2023-03-20 15:12 UTC, nkurunziza1 approved these changes

2023-03-20 15:13 UTC, nkurunziza1 approved these changes

2023-03-20 15:13 UTC, Abdulkeza commented on src/services/googleAuth.js
> +               console.log(token)
remove console log

2023-03-20 15:13 UTC, Abdulkeza commented on src/services/googleAuth.js
> +                            // }
remove this comments

2023-03-20 15:13 UTC, Abdulkeza commented on src/services/googleAuth.js
> +  //   });
remove this

2023-03-21 16:54 UTC, leandreAlly approved these changes

2023-03-21 17:33 UTC, Abdulkeza approved these changes

2023-03-21 17:33 UTC, merged