ch API documentation with swagger 184637127
atlp-rwanda/destructors-ec-bn pull request #11
Opened 2023-03-10 12:18 UTC by JENNY-257

What does this PR do?

This pull request  set up API documentation with  swagger.

Description of Task to be completed?
. API documentation with swagger:we will be able to have document contains data with  CRUDE operation.

How should this be manually tested?

installation
1.Clone repository by running this command

      git clone https://github.com/atlp-rwanda/destructors-ec-bn.git

2.Go in repository by running
     cd destructors-ec-bn
3.Install necessary dependences by running \
npm install
And also  run this comand npm install swagger-ui-express swagger-jsdoc

4.Run the development server by running npm run dev.at this point server will be starting reload.

5.Use this URL to access api documentation with swagger 

url= " http://localhost:3000/api-docs/"

Any background context you want to provide?
- none

What are the relevant pivotal tracker/Trello stories?

- tracker: 184637127
Screenshots (if appropriate)

- none
Questions:

- none

2023-03-11 10:18 UTC, mjeanbosco19 requested changes
**Great job @JENNY-257** 
But you should provide description of your PR

2023-03-11 13:10 UTC, mjeanbosco19 approved these changes

2023-03-11 15:43 UTC, ba-lambert approved these changes

2023-03-11 21:10 UTC, Abdulkeza requested changes
Left feedback below!

2023-03-11 21:10 UTC, Abdulkeza commented on package.json
> +
@JENNY-257 , do you think this can work without a Comma?
it seems like you added swagger-ui-express package manually, add comma after this package

2023-03-13 09:55 UTC, leandreAlly commented on src/swagger.js
> +        description: 'This a simple api for mastering about back-end which will do an ecommerce server',
we're lacking Schemes here?

2023-03-13 09:56 UTC, leandreAlly commented on src/swagger.js
> +        description: 'This a simple api for mastering about back-end which will do an ecommerce server',
You can checkout here https://portifolio-website.up.railway.app/api-docs/ what is Schemes!

2023-03-13 21:36 UTC, Abdulkeza approved these changes

2023-03-13 21:36 UTC, merged