#184637134 feat:user-login
atlp-rwanda/destructors-ec-bn pull request #23
Opened 2023-03-16 15:11 UTC by nkurunziza1

**Description**:

This pull request adds login functionality to the project. Users can now securely log in to their accounts using their email and password. The login feature has been implemented according to industry best practices for security and user experience.

**Testing**:

The login functionality has been tested locally with multiple test accounts to ensure that users can successfully log in and that any errors or issues are properly handled.

**Checklist**:

The code has been thoroughly tested locally and all tests pass.
The login feature has been implemented according to industry best practices.
Security measures, such as encryption of user passwords, have been properly implemented.

2023-03-17 09:08 UTC, denislohan requested changes
1. you commits are named wrong
2. you have not added reviewers

2023-03-17 09:53 UTC, mjeanbosco19 commented
@nkurunziza1 Your tests failed on CircleCI, try to work on it

2023-03-20 03:26 UTC, Abdulkeza requested changes
@nkurunziza1 , why do wee need **user.controller.js** and **user-login-controller.js**?

Please can we have either _user.controller.js*_ or _auth.controller.js_*

2023-03-20 03:26 UTC, Abdulkeza commented on src/controllers/user-login-controller.js
> +  res.json({ message: `welcome, ${user.firstname} ` });
what will happen if an invalid user passed in this func?
it's better to catch the errors that might happen.

`const protectedRouteHandler = async (req, res, user) => {
  try {
    res.json({ message: `welcome, ${user.firstname} ` });
  } catch (error) {
    return res.status(500).json({ message: 'Internal server error' });
  }
};`

2023-03-20 09:51 UTC, leandreAlly requested changes

2023-03-20 09:51 UTC, leandreAlly commented on src/routes/api/user-login.routes.js
> +LoginRouter.post('/users/login', loginUser);
you're not following the our folder structure convention, we suppose to only have single routes for users.
why did you added new file?

2023-03-20 09:51 UTC, leandreAlly commented on src/controllers/user-login-controller.js
> +import passport from 'passport';
also this controller must be binded into user.controller.js

2023-03-20 15:41 UTC, ba-lambert commented on src/routes/api/user.routes.js
> +route.post('/users/login', loginUser);
Check this endpoint mhn

2023-03-20 15:45 UTC, ba-lambert commented
And also your test coverage  is still under 81

2023-03-20 15:54 UTC, mjeanbosco19 commented
If possible squash commits to easy rebase issue

2023-03-20 18:53 UTC, merged