ft(two-factor-auth):generate 2fa to the user)
atlp-rwanda/destructors-ec-bn pull request #32
Opened 2023-03-22 09:37 UTC by buka1calvin

2023-03-22 18:56 UTC, Abdulkeza requested changes
left feedback bellow

2023-03-22 18:56 UTC, Abdulkeza commented on src/services/emailValidation.service.js
> +const validOTPmail=async(user,otp,token)=>{
please let's use understandable function names and variable names

2023-03-22 18:56 UTC, Abdulkeza commented on src/services/emailValidation.service.js
> +    .catch(error=>console.log(error))
we are supposed to have a function that sends emails, what you only need is to pass data and subject.  you can ask the team.

2023-03-22 18:56 UTC, Abdulkeza commented on src/utils/verifyOTP.js
> +        return res.send("invalid OTP!")
please let's use the same structure  ie `res.status(statusCode).json({message: message})`

2023-03-22 18:56 UTC, Abdulkeza commented on src/utils/verifyOTP.js
> +     const user=await OTP.findOne({
are you finding a user? or is OTP?

2023-03-22 18:56 UTC, Abdulkeza commented on src/utils/verifyOTP.js
> +    res.send("logged in successfully")
Please you are supposed to send token once a user logged in! also remember to include status code and use JSON format

2023-03-22 19:08 UTC, buka1calvin commented on src/services/emailValidation.service.js
> +    .catch(error=>console.log(error))
i'm waiting for the team so that i can pull kairos changes

2023-03-23 17:18 UTC, katros1 approved these changes

2023-03-24 10:44 UTC, katros1 commented on src/services/emailValidation.service.js
> +    .catch(error=>console.log(error))
@buka1calvin try to check in service there a service for sending email

2023-03-24 11:12 UTC, nkurunziza1 approved these changes

2023-03-24 11:32 UTC, ba-lambert requested changes
Seller is the one have to receive the OTP not buyer

2023-03-24 13:25 UTC, Abdulkeza approved these changes

2023-03-24 13:26 UTC, JENNY-257 approved these changes

2023-03-24 13:26 UTC, merged