feat(product availability): mark product as available/unavailable
atlp-rwanda/destructors-ec-bn pull request #38
Opened 2023-03-28 09:19 UTC by JENNY-257

2023-03-31 14:05 UTC, leandreAlly approved these changes

2023-04-03 07:00 UTC, buka1calvin approved these changes

2023-04-03 07:46 UTC, katros1 requested changes
try to catch the error for the categoryId, In case the user insert the id which is not UUID type

2023-04-03 09:59 UTC, katros1 approved these changes

2023-04-03 10:02 UTC, Abdulkeza approved these changes

2023-04-03 10:02 UTC, merged