#184637150 product review
atlp-rwanda/destructors-ec-bn pull request #47
Opened 2023-04-06 14:18 UTC by JENNY-257

What does this PR do?

     - A buyer should be able to make review on product including rating and feedback

Description of Task to be completed?

      - When a buyer has bought the product  must be able  to make a review  on that product has purchased.

 
How should this be manually tested?

        - Clone the repository
        - Change the directory to destructors-ec-bn by running cd destructors-ec-bn in you terminal
        - Checkout ft-product-review-184637150 branch by running git checkout ft-product-review-184637150 in you terminal
        - open .env.example to check how you can create you .env file
        - Create your .env file
        - Then install dependencies and devdependencies used by running npm install in you terminal
        - To create the models used in this project run npm migrate
        - Run the server by running npm run dev in your terminal
           open you browser and in URL field type http://localhost:PORT/api-docs (the PORT is the port you have written in your .env 
             file. The default port is 3000)
        - Login users  as buyer using /api/v1/users/login endpoint
        - Review product by using  this endpoint  /api/v1/products/:id/reviews

Any background context you want to provide?
           None

What are the relevant pivotal tracker/Trello stories?
           tracker: #184637150

2023-04-15 18:44 UTC, ba-lambert commented
check your test builc

2023-04-15 19:48 UTC, ba-lambert commented on src/controllers/productReview.controller.js
> +    const product = await Products.findOne({ where: { id: productId } });
For best practice this should not be in controller should be in middleware or services

 thanks @ba-lambert  , I have fixed comments

2023-04-15 19:48 UTC, ba-lambert commented on src/controllers/productReview.controller.js
> +    const existingReview = await Reviews.findOne({
Also this

2023-04-15 19:48 UTC, ba-lambert commented on src/database/migrations/20230316084558-create_products_table.js
> +      averageRating: {
Here I think you should add migration modification not destroy hard code like you did  here @JENNY-257

2023-04-15 19:48 UTC, ba-lambert commented on src/controllers/productReview.controller.js
> +    const totalRatings = reviews.reduce((acc, cur) => acc + cur.rating, 0);
can you try to use middleware @JENNY-257

2023-04-16 21:03 UTC, Abdulkeza requested changes
@JENNY-257  you did a great JOB,

try to solve the feedback below and you are good to go 
![image](https://user-images.githubusercontent.com/78693678/232342009-47a34fca-543e-4806-80d4-8786edccd168.png)
:fire:

2023-04-16 21:03 UTC, Abdulkeza commented on __test__/product.test.js
> +      .post('/api/v1/products/9974076f-e16a-486f-a923-362ec1747a12/reviews')
Can we stop hard coding IDs like this, please?

means you can use the one you created above.

2023-04-16 21:03 UTC, Abdulkeza commented on __test__/product.test.js
> +import { Reviews } from '../src/database/models';
if we don't need this, please can we remove them here?

2023-04-16 21:03 UTC, Abdulkeza commented on src/ validations/productReview.validation.js
> +  };
Leave one empty line at the end / Bottom of the file

2023-04-16 21:03 UTC, Abdulkeza commented on src/controllers/productReview.controller.js
> +    const product = await Products.findOne({ where: { id: productId } });
Great @ba-lambert , 

@JENNY-257  we have function called **findProductById** under _product.service.js_ 
let's make use of the function that's already in place.


good thanks @Abdulkeza 
I'm done  to work on  comments

2023-04-17 08:06 UTC, ba-lambert approved these changes

2023-04-17 12:29 UTC, nkurunziza1 approved these changes
### ### ****

2023-04-17 12:39 UTC, merged