Bg fix add get sales
atlp-rwanda/destructors-ec-bn pull request #59
Opened 2023-04-24 09:18 UTC by divinecharlotte

2023-04-25 15:24 UTC, ba-lambert requested changes

2023-04-25 15:24 UTC, ba-lambert commented on src/controllers/sale.controller.js
> +
Try to not use models inside controllers

2023-04-25 15:24 UTC, ba-lambert commented on src/routes/api/sale.routes.js
> +route.get('/', extractToken, checkRole(['seller','admin']),getSales );
Also add password check middlware here

2023-04-25 17:03 UTC, katros1 commented on src/controllers/product.controller.js
>        if (categoryId) where.categoryId = categoryId;
try to check also if the category id is uuid

2023-04-26 22:13 UTC, ba-lambert submitted a review, later dismissed

2023-04-26 22:13 UTC, ba-lambert commented on src/controllers/product.controller.js
>        const products = await Products.findAll({ where });
Try to not interact with database inside controllers

2023-04-30 18:19 UTC, katros1 approved these changes

2023-04-30 18:23 UTC, katros1 commented
Try to check your tests are failing!!!

2023-05-01 07:36 UTC, ba-lambert commented on src/controllers/sale.controller.js
> +
You did not resolve the issue

2023-05-01 07:43 UTC, ba-lambert commented on src/controllers/sale.controller.js
> +
I mean that you have to respect the folder structuring

2023-05-02 12:47 UTC, katros1 approved these changes

2023-05-02 13:02 UTC, buka1calvin approved these changes

2023-05-02 13:03 UTC, buka1calvin commented
divine please rebase

2023-05-16 16:32 UTC, leandreAlly approved these changes

2023-05-17 07:40 UTC, mjeanbosco19 approved these changes

2023-05-17 08:24 UTC, JENNY-257 approved these changes

2023-05-18 07:28 UTC, Abdulkeza approved these changes

2023-05-18 07:30 UTC, merged