bg-fx-2fa-and-prod-wishlist add changes requested
atlp-rwanda/destructors-ec-bn pull request #60
Opened 2023-04-24 11:59 UTC by buka1calvin

### What does this PR do?

- [x] otp must maximum number  must not exceed 6 digits and must be detected trough validation
- [x] error message must be meaningful 

### How should this be manually tested?

**Installation**
**1. Clone the repository by running** 
```
git clone https://github.com/atlp-rwanda/destructors-ec-bn.git
```
**2. Navigate to the project directory by running cd destructors-ec-bn.**
```
cd destructors-ec-bn
```
```
 cd  bg-fix-add-getSales
```
**3. Install the necessary dependencies by running npm install.**
```
npm install
```
**4. run migrations**
```
 npx sequelize-cli db:migrate
```
**6. Run the development server by running npm run dev. This will start the server using Nodemon, which will automatically reload the server when changes are made to the code.**
```
npm run dev
```
**7. Run the tests by running npm run test** 
```
npm run test
```
### Any background context you want to provide?

### Questions:

- none

2023-04-26 09:03 UTC, leandreAlly requested changes

2023-04-26 09:03 UTC, leandreAlly commented on src/controllers/wishlist.controller.js
> +        res.status(500).json({error: error.message.replace(/[^a-zA-Z0-9 ]/g, '')})
remove this kind of error displaying on response to the user I had designed because it was for Joi error messsage displaying

2023-04-26 12:10 UTC, buka1calvin commented on src/controllers/wishlist.controller.js
> +        res.status(500).json({error: error.message.replace(/[^a-zA-Z0-9 ]/g, '')})
actually when i use these regular expressions they show me clearly the error where it's happening

2023-05-02 10:31 UTC, mjeanbosco19 reviewed
@buka1calvin  **Great job** Please, Rebase develop branch to have all tests passing

2023-05-02 10:43 UTC, mjeanbosco19 approved these changes

2023-05-02 12:20 UTC, katros1 approved these changes

2023-05-02 18:46 UTC, ba-lambert commented
This description does not contain what is going to be tasted

2023-05-02 18:54 UTC, ba-lambert approved these changes

2023-05-03 07:40 UTC, Abdulkeza approved these changes

2023-05-03 07:41 UTC, merged