Bg fix get users
atlp-rwanda/destructors-ec-bn pull request #68
Opened 2023-05-25 20:54 UTC by nkurunziza1

**What does this PR do?**
- Get all users according to the last in first out
**Checklist**
- [x] Get user 
- [x] Last in first out 

**How this should be manually testing**

- clone  this [repo](https://github.com/atlp-rwanda/destructors-ec-fe.git) 
- got to the repo directory by  writing this `cd  destructors-ec-bn in terminal
- write this command in terminal `git checkout bg-fix-get-users
- `npm run dev`
- Testing on swagger by getting all user according to the date

2023-05-26 10:37 UTC, mjeanbosco19 approved these changes

2023-05-26 13:19 UTC, katros1 approved these changes

2023-05-29 10:25 UTC, JENNY-257 approved these changes

2023-06-01 17:30 UTC, leandreAlly requested changes

2023-06-01 17:30 UTC, leandreAlly commented on src/controllers/user.controller.js
> +      // <---------this is for generating the one time password------->
remove this comments

2023-06-01 17:30 UTC, leandreAlly commented on src/controllers/user.controller.js
> +      const HTMLText = `<p style='font-size: 15px'><strong> Hi <br> <br>
why are you hard coding this URL

2023-06-05 09:03 UTC, ba-lambert approved these changes

2023-06-05 09:10 UTC, katros1 approved these changes

2023-06-05 11:10 UTC, Abdulkeza approved these changes
Well Done

2023-06-05 11:11 UTC, merged