Ch hound ci with badges 184637123
atlp-rwanda/destructors-ec-bn pull request #7
Opened 2023-03-08 23:57 UTC by nkurunziza1

2023-03-09 11:21 UTC, mjeanbosco19 requested changes
1. I noticed that you have 8 commits, I recommend you To "squash" in Git means to combine your multiple commits into one commit or at least not above two commits.
2. Which issue did you face with? I noticed that you have changed every single quote to double quote which can cause conflict for those who have single quote?

2023-03-10 08:32 UTC, Abdulkeza commented
> 1. I noticed that you have 8 commits, I recommend you To "squash" in Git means to combine your multiple commits into one commit or at least not above two commits.
> 2. Which issue did you face with? I noticed that you have changed every single quote to double quote which can cause conflict for those who have single quote?

for a double quote, that means as a team, you are going to use the same structure. ie only double quote allowed.

2023-03-10 12:44 UTC, leandreAlly approved these changes

2023-03-10 12:47 UTC, mjeanbosco19 requested changes
**Great job @nkurunziza1!**
However, you should work on this.

1. Squash your 10 commits into one or at least two commits.
2. Remember to write description of your PR.

2023-03-10 13:39 UTC, ba-lambert approved these changes

2023-03-13 07:23 UTC, Abdulkeza approved these changes

2023-03-13 07:24 UTC, merged