chore(Integrate CircleCi and Coveralls badges ):testing environment
atlp-rwanda/destructors-ec-bn pull request #8
Opened 2023-03-09 05:56 UTC by divinecharlotte

### What does this PR do?

- Integrate CircleCI with the readme badge
- Integrate Coeralls with readme badge

### Description of Task to be completed?

1. set up local tests
2. integrate circle-Ci: This is required to automatically run tests and other preliminary build steps required to ship the next iteration of the product
3. Integrate Coeralls: This is to ensure we are properly informed just how well our code base is tested which in turn provides quality assurance for the product

### How should this be manually tested?

**Installation**
**1. Clone the repository by running** 
```
git clone https://github.com/atlp-rwanda/destructors-ec-bn.git
```
**2. Navigate to the project directory by running cd destructors-ec-bn.**
```
cd destructors-ec-bn
```
**3. Install the necessary dependencies by running npm install.**
```
npm install
```
**4. Run the development server by running npm run dev. This will start the server using Nodemon, which will automatically reload the server when changes are made to the code.**
```
npm run dev
```
**5. Run the tests by running npm run test** 
```
npm run test
```
### Any background context you want to provide?

- none

### What are the relevant pivotal tracker/Trello stories?

- Tracker: 184637125
- Tracker: 184637124
### Screenshots (if appropriate)

- none

### Questions:

- none

2023-03-09 07:16 UTC, mjeanbosco19 reviewed
You did a great job @divinecharlotte keep it up!!!  
I noticed that your Pull Request is missing the task ID at the beginning of the name. As a reminder, we require that all our Pull Requests follow the naming convention of starting with the task ID and then a brief description name.

2023-03-09 11:15 UTC, Abdulkeza approved these changes, later dismissed

2023-03-09 11:15 UTC, Abdulkeza commented on .circleci/config.yml
> +      repo_token: REPO_TOKEN
Have you added this Environment variable in github secretes and it's value?

2023-03-09 11:27 UTC, Abdulkeza requested changes
add one test for testing

2023-03-09 11:42 UTC, mjeanbosco19 requested changes
You should add coverage directory to .gitignore.  As reminder, you should add Label on your PR like WIP or Ready for Review.

2023-03-09 14:59 UTC, mjeanbosco19 approved these changes
Amazing!!! Keep it up @divinecharlotte

2023-03-09 15:35 UTC, leandreAlly approved these changes

2023-03-09 15:50 UTC, istafrica-dennw requested changes
1. There is no build
2. there is coverage 

on the budges

2023-03-09 19:53 UTC, Abdulkeza commented on coverage/clover.xml
> +</coverage>
@divinecharlotte , remember to put coverage folder in **gitignore**

ex: coverage

2023-03-09 19:54 UTC, Abdulkeza requested changes
remember to add coverage in **gitignore**

2023-03-10 09:37 UTC, Abdulkeza requested changes
Please make sure the conflicts are resolved correctly

2023-03-10 09:37 UTC, Abdulkeza commented on .babelrc
>    ]
What it this @divinecharlotte ?

2023-03-10 09:37 UTC, Abdulkeza commented on .babelrc
> +>>>>>>> 3c62b51 (add a single test to check the environment)
please have you resolved conflicts in the perfect way?

2023-03-10 11:22 UTC, Abdulkeza approved these changes

2023-03-10 11:31 UTC, Abdulkeza approved these changes

2023-03-10 11:32 UTC, merged